name: CI

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - node

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 24.x
    - name: install dependencies
      working-directory: ${{ matrix.package }}
      run: npm ci
    - name: run test
      working-directory: ${{ matrix.package }}
      run: npm test
      env:
        CI: true
    - name: lint
      working-directory: ${{ matrix.package }}
      run: npm run lint
    - name: run the cli
      working-directory: ${{ matrix.package }}
      run: node bin/cli.js --help
